FROM node:20-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /app

USER appuser

COPY package*.json ./

RUN npm ci && npm cache clean --force

COPY --chown=appuser:appgroup . .

EXPOSE 3000

CMD ["npm", "run", "dev:docker"]
