services:
  postgres:
    image: postgres:15-alpine
    container_name: grainydays-db
    environment:
      POSTGRES_DB: grainydays
      POSTGRES_USER: grainydays
      POSTGRES_PASSWORD: grainydays_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grainydays -d grainydays"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: grainydays-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app:Z
      - /app/node_modules
      - /app/.svelte-kit
    environment:
      - DATABASE_URL=postgres://grainydays:grainydays_dev@postgres:5432/grainydays
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data: 